version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/app
      - node_modules_volume:/app/node_modules
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
volumes:
  node_modules_volume:
